#!/bin/sh

set -e
set -u
#set -x

## Convert full DN to an LDIF line for the naming attribute (used for root entry)
dn_to_na() {
  echo $1 | cut -d',' -f 1 | sed 's/=/: /'
}

echo_envmode() {
  echo ":: Environment: ${EDULDAP_ENV}"
}

CONFIG_DIR=${OPENLDAP_ETC}/slapd.d
DATABASE_FILE=${EDULDAP_HOME}/bootstrap/databases/${DATABASE}.ldif
SEED_FILE=${EDULDAP_HOME}/bootstrap/seeds/${SEED}.ldif

ADMIN_SECRET_FILE=${ADMIN_SECRET_FILE:-"/dev/null"}

if  [[ -f $ADMIN_SECRET_FILE ]]; then
  ADMIN_SECRET=`cat $ADMIN_SECRET_FILE | tr -d '\n'`
fi

ADMIN_SECRET=${ADMIN_SECRET:-`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`}
DATABASE_SUFFIX=`grep olcSuffix $DATABASE_FILE | head -1 | cut -d':' -f 2 | sed 's/^ //'`
ONA=$(dn_to_na $DATABASE_SUFFIX)
NNA=$(dn_to_na $BASE_DN)

## Load external variables
#set -a
#ENVFILE=${EDULDAP_HOME}/etc/envfile
#[ -f $ENVFILE ] && . $ENVFILE && echo "Loading $ENVFILE..."
#set +a

#if [[ $EUID -ne 0 ]]; then
#  echo "This script must be run with root privileges (as root or via sudo)" 1>&2
#  exit 1
#fi
