#!/bin/sh

set -e
set -u
#set -x

## Convert full DN to an LDIF line for the naming attribute (used for root entry)
function dn_to_na {
  echo $1 | cut -d',' -f 1 | sed 's/=/: /'
}

function echo_envmode {
  echo ":: Environment Mode: ${ENV_MODE}"
}
## These variables are for private use, unlikely to change
DATA_DIR=/var/lib/openldap/openldap-data
EDULDAP=/etc/eduldap
ETC=/etc/openldap
CONFIG_DIR=${ETC}/slapd.d
RUN_DIR=/var/run/openldap
SOCK_DIR=/var/lib/openldap/run

## These variables can be passed on commandline, Dockerfile, etc to change behaviour
ENV_MODE=${ENV_MODE:-development}
AUTO_INIT=${AUTO_INIT:-true}
ADMIN_SECRET=${ADMIN_SECRET:-`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`}
BASE_DN=${BASE_DN:-'dc=demo,dc=university'}
DEBUG_LEVEL=${DEBUG_LEVEL:-256}
DATABASE=${DATABASE:-default}
SCHEMA="core cosine nis misc pmi ppolicy dyngroup inetorgperson eduperson schac ssh voperson"
SEED=${SEED:-default}
RESET=${RESET:-false}
TIDY=${TIDY:-true}
SLAPD_URLS="ldap:/// ldapi:///"
SLAPD_OPTIONS="  "

## Derived from user options
DATABASE_FILE=$EDULDAP/initial_config/databases/$DATABASE.ldif
SEED_FILE=$EDULDAP/initial_config/seeds/$SEED.ldif
DATABASE_SUFFIX=`grep olcSuffix $DATABASE_FILE | head -1 | cut -d':' -f 2 | sed 's/^ //'`
ONA=$(dn_to_na $DATABASE_SUFFIX)
NNA=$(dn_to_na $BASE_DN)

## Load external variables
set -a
[ -f /etc/eduldap/envfile ] && . /etc/eduldap/envfile
set +a

#if [[ $EUID -ne 0 ]]; then
#  echo "This script must be run with root privileges (as root or via sudo)" 1>&2
#  exit 1
#fi